### ISSUE TITLE
Implement Human-in-the-loop features

### ISSUE THREAD

**Issue by avhhh** [iter8-tools/iter8-kui#1]
**To-do Tasks**
[exprCreate branch]
- [x] ~~Trigger Decision Tab~~
- [x] ~~Implement Loading for Decision Tab~~
- [x] ~~Render test for _react-minimal-pie-chart_~~ (ApexCharts)
- [x] ~~Import MetricsConfig Methods to autofill dropdown~~
- [x] ~~Setup rewards checkbox logic for metrics~~

[iter8-req branch]
- [x] ~~Organize JSON data model when submit is pressed~~
- [x] ~~Transfer the data to \<DecisionForm\>~~ (eventBus)
- [X] ~~Run AJAX call on button click~~

**Interface Decision Tab**
- [x] ~~Parse information to show Win Probabilities~~
- [x] ~~Parse traffic information to show sliders~~
- [x] ~~Parse metric information to show values~~
- [x] ~~Convert input into organized data for vs parsing function~~
- [x] ~~Functionality for apply button (#55)~~

**Others**
- [x] ~~Add last_state functionality?~~
- [x] ~~Figure out virtual service configuration scheme~~
- [x] ~~Run through demo scenarios A & B~~

**Bug Fixes/Styling**
- [x] ~~FIX that carbon slider??? literally refuses to be reset!!!!~~
- [x] ~~Style the decision tab interface~~
- [x] ~~Bookinfos application not rendering CSS styles~~
~~Optional: switch apexCharts -> carbon chart~~ (not supported)
