### ISSUE TITLE
Modifications to the HIL command

### ISSUE THREAD

**Issue by sushmarchandran** [iter8-tools/iter8-kui#24]
- [ ] Code restructuring in accordance to the PR comments `https://github.com/iter8-tools/iter8-kui/pull/21`
- [x] Change name of command from `create exp` to `iter8 create experiment`
- [x] Change analytics URL to be able to use custom url

Changes to the experiment creation form:
- [x] Align the form elements
- [x] Re-align elements to have `Observe` button at the end
- [x] Add dropdown to select Experiment type: `Automated` vs `HIL`
- [x] Validation for clicking `Observe` without adding a metric
- [x] Test reward metric
- [x] Change `Select Candidates` color
- [x] Pass only necessary metrics to the analytics service (Currently all metrics from the ConfigMap are being passed)- The entire ConfigMap will now be passed to the analytics service
- [x] Add Advanced options in request parameters-  can be ignored for now- add to automated experiments
- [x] Change `Observe` to `Create Experiment`
- [x] Add `Info:` before tags
- [x] Remove baseline from candidate's dropdown list (deployment cannot be baseline and candidate)- Check is being performed before form submission
- [x] Add non-existant baseline/candidate options- can be ignored for now- add to automated experiments
- [x] Change `metric` to `criteria`

Changes to the decision tab:
Reference: 
1. https://wireframe.cc/pro/pp/a461605a2332600
2. https://wireframe.cc/p3DlAu
- [x] Redesign decision tab to include all information from the response JSON
- [x] Redesign the functionality of `Refresh` to call analytics with the experiment JSON every time
- [x] Remove `Refresh` button bug that creates new candidates
- [x] Change `Refresh` to `Get Assessment`
- [x] Css Border for sections 
- [x] Add appropriate message and check if criteria is not available
- [x] Add appropriate message and check if advanced Statistics is not available
- [x] Add titles for each section with css
1. Winner Assessment
   - [x] Check if winner assessment performs as expected
2. Win Probabilities
   - [x] Refresh bug should not increase the number of services in the pie chart
3. Traffic Split
   - [x] Toggle functionality can be modified
   - [x] Move `Apply` and `Reset` buttons lower
   - [x] Change `reset` to `Reset Traffic Split`? 
4. Metrics Comparison
   - [x] Restructure the entire table based on new design
   - [x] Allow column sort
   - [x] Add Rollback column
   - [x] Add Request count below each service
   - [x] Design and implement on Hover feature for metric value that don't satisfy the criteria set
5. Advanced Statistics
   - [x] Design and implement according to the wireframe
   - [ ] Allow column sort
6. Roll Forward/Roll Back 
   - [x] Design Roll forward/Rollback option
   - [x] Hover should inform user what it means
   - [x] Disable `Get Assessment` after Roll Forward/Roll back
   - [x] Change End Experiment:hover color

**Comment by sushmarchandran** [comment]
Modifications to HIL command after playback meeting:

- [ ] Run analytics Service through any endpoint
- [ ] What happens if there is no kubeconfig?
- [ ] Disable create exp button until we have minimum needed entries

1. Exp tab:
    - [ ] Check if only numeric values are entered for values
    - [x] Disable add Criterion button when create experiment
    - [ ] Some padding around each criterion
    - [ ] What happens if experiment create fails?
    - [ ] Candidate deployment should have text input option as well
2. Decision tab
    - [ ] Add legend text 
    - [ ] Metrics Comparison:
        - [ ] Distinguish Baseline and candidate versions
        - [ ] Show the total request count just below the name of the version or on hover
        - [ ] Color the appropriate threshold related information
    - [ ] Print current traffic split info- get it from last state
    - [x] Advanced stats for only ratio stats info
    - [ ] Make Apply Traffic split faster
    - [ ] Review padding for each section
    - [x] Can Advanced statistics not have a button and a header?
    - [ ] End experiment can have a dropdown to shift traffic to any version
    - [ ] Add last state to second Get Assessment
    - [ ] Sort Table functionality
    - [ ] Move reset traffic and Apply traffic a little below the dropdown
    - [ ] Tables should include info about which is baseline and which is candidate
    - [x] Remove request count from the sample dummy json
    - [x] Remove request count from the header

**Comment by sushmarchandran** [comment]
Comments after June 26 2020 Playback

KUI To do:

- [ ] Advanced statistics keys can be stored elsewhere
- [ ] Validation for comma separated 
- [ ] Delete Criterion disabled after create exp
- [ ] Service based create experiment
- [ ] High Level Review adds new rows every time we click on get assessment
- [ ] Call it high level overview
- [ ] Reasonable defaults for criteria
- [ ] Traffic Assessment section should say Choose Goal for Traffic Split and not Choose Algorithm
- [ ] No winner assessment-> Not enough data 
- [ ] Incorporate Win prob into high level overview
- [ ] Hide Criteria assessment also?
- [ ] Simplify Criteria section
- [ ] Change unit of experiment to Host or service
